name: CICD using Maven and Jenkins
on: 
  push:
  workflow_dispatch:
jobs:
  CICDJob:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo on ubuntu server
        uses: actions/checkout@v4
      - name: Install Java and Maven on ubuntu server
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build the source code and generate .war file  
        run: mvn package
      - name: connect to LAB and deploy code on tomcat9
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: '13.201.4.202'
          user: 'labuser'
          pass: 'Nuvelabs123$'
          port: 22
          connect_timeout: 10s
          first_ssh: |
             sudo curl -l -u admin: 11e9f71a003a87f3503a02aa1f1be4d910 http://localhost:8080/job/DeploymentJob/build?token=Token1
